package com.woozie.balancingrobot.service

data class SpeedLoopDiagnosticState(
    val enabled: Boolean = true,
    val stale: Boolean = true,
    val feedbackSequence: Long? = null,
    val feedbackAgeMs: Double? = null,
    val feedbackRateHz: Double = 0.0,
    val loopRateHz: Double = 0.0,
    val leftRawStepsPerSec: Int? = null,
    val rightRawStepsPerSec: Int? = null,
    val leftCmPerSec: Double? = null,
    val rightCmPerSec: Double? = null,
    val meanCmPerSec: Double? = null,
    val filteredCmPerSec: Double? = null,
    val targetCmPerSec: Double = 0.0,
    val appliedTargetCmPerSec: Double = 0.0,
    val speedCommandSlewLimited: Boolean = false,
    val errorCmPerSec: Double? = null,
    val correctionDeg: Double = 0.0,
    val integralCorrectionDeg: Double = 0.0,
    val trimDeg: Double = 0.0,
    val effectiveTargetDeg: Double = 0.0,
    val autoTrimState: String = "REST",
    val restTrimDeg: Double = 0.0,
    val settledDurationSec: Double = 0.0,
    val quiet: Boolean = false,
    val autoTrimDeg: Double = 0.0,
    val requestedLeanDeg: Double = 0.0,
    val appliedLeanDeg: Double = 0.0,
    val brakeCorrectionDeg: Double = 0.0,
    val userCommandActive: Boolean = false,
    val saturated: Boolean = false,
    val slewLimited: Boolean = false,
)
